Repository AnnPkGit/DiplomaWork, pull requests merged in 2023-11, with the labels that each got.

#100 Verification messages
  Src/Application/Auth/Commands/ConfirmPhoneCommand/ConfirmPhone.cs
  Src/Application/Auth/Commands/SendVerifyMsgBySms/SendVerifyMsgBySms.cs
  Src/Application/Common/Interfaces/IConfirmPhoneService.cs
  Src/Application/Common/Interfaces/IFourDigitCodeGenerator.cs
  Src/Application/Common/Interfaces/ISmsVerificationConfirmationService.cs
  Src/Application/Common/Interfaces/ISmsVerify.cs
  Src/Infrastructure/Configurations/SmsVerifyOptions.cs
  Src/Infrastructure/ConfigureServices.cs
  Src/Infrastructure/Infrastructure.csproj
  Src/Infrastructure/Services/FourDigitCodeGeneratorService.cs
  Src/Infrastructure/Services/SmsVerificationConfirmationService.cs
  Src/Infrastructure/Services/SmsVerifyService.cs
  Src/WebDiplomaWork/ConfigureServices.cs
  Src/WebDiplomaWork/Controller/AuthController.cs
  Src/WebDiplomaWork/OptionsSetup/SmsVerifyOptionsSetup.cs
Labels: enhancement

#103 Fixed bugs and issues
  Src/Domain/Entities/Quote.cs
  Src/Domain/Entities/ReToast.cs
  Src/Domain/Entities/Reply.cs
  Src/Infrastructure/ConfigureServices.cs
  Src/Infrastructure/Services/MediaStorage.cs
Labels: bug

#108 Fixed a few bugs and added some new logic
  Src/Application/Accounts/Commands/UpdateAccountDetail/UpdateAccountDetailCommand.cs
  Src/Application/BaseToasts/Queries/GetToastWithContentById/GetToastByIdQuery.cs
  Src/Application/BaseToasts/Queries/GetToastsMarkedByAccount/GetToastsMarkedByAccountQuery.cs
  Src/Application/BaseToasts/Queries/Models/BaseToastWithContentBriefDto.cs
  Src/Application/BaseToasts/Queries/Models/BaseToastWithContentDto.cs
  Src/Application/Common/Interfaces/IIncludeCurrentUserService.cs
  Src/Application/Common/Mappings/MappingProfile.cs
  Src/Application/ReToasts/Commands/DeleteReToastByToastId/DeleteReToastByToastIdCommand.cs
  Src/Application/Replies/Queries/GetRepliesByToast/GetRepliesByToastQuery.cs
  Src/Application/Replies/Queries/Models/ReplyBriefDto.cs
  Src/Application/Users/Commands/UpdateUserPassword/UpdateUserPasswordCommandValidation.cs
  Src/WebDiplomaWork/Controller/ReToastController.cs
Labels: bug, enhancement

#110 Account search system
  Src/Application/Accounts/Queries/GetAccountsByLoginOrName/GetAccountsByLoginOrNameQuery.cs
  Src/Infrastructure/Persistence/MIgrations/ApplicationDbContextModelSnapshot.cs
  Src/WebDiplomaWork/Controller/AccountController.cs
  Src/WebDiplomaWork/Controller/ReToastController.cs
Labels: enhancement

#115 Implement the GetToastsFromFollows Query
  Src/Application/Auth/Commands/LoginUserUsingSession/LoginUserUsingSessionCommand.cs
  Src/Application/BaseToasts/Queries/GetToastsFromFollows/GetToastsFromFollowsQuery.cs
  Src/Application/BaseToasts/Queries/GetToastsWithMediaItemsByAccount/GetToastsWithMediaItemsByAccountQuery.cs
  Src/Application/Users/Queries/GetCurrentUser/GetCurrentUserQuery.cs
  Src/WebDiplomaWork/Controller/BaseToastController.cs
Labels: enhancement
